import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [input, setInput] = useState('')
  const [names, setNames] = useState([])

  const submit = async () => {
    const res = await fetch('api/rimworld-colonists', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ input }),
    })
    const data = await res.json()
    console.log(data)
    const result = JSON.parse(data.result)
    setNames(result)
    console.log(names)
    
  }

  return (
    <>
      <Head>
        <title>Rimword Ai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-7xl mx-auto py-12'>
        <h2 className='text-2xl font-bold text-center pb-2'>Rimword Name Generator</h2>

        <div className='flex flex-col gap-4 justify-center w-1/3 mx-auto'>
          <div className='relative'>
            <textarea 
              rows={3}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              className='w-full border-2 border-gray-300 bg-white p-4 rounded-lg text-sm focus:outline-none resize-none'
              placeholder='Enter the amount of names you want.'
            />
            
          </div>
          <button type='button' onClick={submit} className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>
            Generate
          </button>

          <ul>
            {names && names.length > 0 ? (
              names.map((person) => (
                <li key={person[0]}>
                  {person[0]} "{person[1]}" {person[2]}
                </li>
              ))
            ) : (
              <li>No data available</li>
            )}
          </ul>



        </div>

      </div>

    </>
  )
}
